config/routes.rb
Repaso::Application.routes.draw do
  resources :categorias

  resources :galerias

  get "estaticas/vista1"

  get "estaticas/vista2"

  get "estaticas/vista3"

  get "estaticas/vista4"
  
  match 'vistaUno' => 'estaticas#vista1'
  match 'vistaDos' => 'estaticas#vista2'
  match 'vistaTres' => 'estaticas#vista3'
  match 'vistaCuatro' => 'estaticas#vista4'

   root :to => 'estaticas#vista1'

end

app/models/categoria.rb
class Categoria < ActiveRecord::Base
	has_many :galerias
end

app/models/galeria.rb
class Galeria < ActiveRecord::Base
  belongs_to :categoria
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categorias_controller.rb
class CategoriasController < ApplicationController
  # GET /categorias
  # GET /categorias.json
  def index
    @categorias = Categoria.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categorias }
    end
  end

  # GET /categorias/1
  # GET /categorias/1.json
  def show
    @categoria = Categoria.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @categoria }
    end
  end

  # GET /categorias/new
  # GET /categorias/new.json
  def new
    @categoria = Categoria.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @categoria }
    end
  end

  # GET /categorias/1/edit
  def edit
    @categoria = Categoria.find(params[:id])
  end

  # POST /categorias
  # POST /categorias.json
  def create
    @categoria = Categoria.new(params[:categoria])

    respond_to do |format|
      if @categoria.save
        format.html { redirect_to @categoria, notice: 'Categoria was successfully created.' }
        format.json { render json: @categoria, status: :created, location: @categoria }
      else
        format.html { render action: "new" }
        format.json { render json: @categoria.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categorias/1
  # PUT /categorias/1.json
  def update
    @categoria = Categoria.find(params[:id])

    respond_to do |format|
      if @categoria.update_attributes(params[:categoria])
        format.html { redirect_to @categoria, notice: 'Categoria was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @categoria.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categorias/1
  # DELETE /categorias/1.json
  def destroy
    @categoria = Categoria.find(params[:id])
    @categoria.destroy

    respond_to do |format|
      format.html { redirect_to categorias_url }
      format.json { head :ok }
    end
  end
end

app/controllers/estaticas_controller.rb
class EstaticasController < ApplicationController
  def vista1
  end

  def vista2
  end

  def vista3
  end

  def vista4
  end

end

app/controllers/galerias_controller.rb
class GaleriasController < ApplicationController
  # GET /galerias
  # GET /galerias.json
  def index
    @galerias = Galeria.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @galerias }
    end
  end

  # GET /galerias/1
  # GET /galerias/1.json
  def show
    @galeria = Galeria.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @galeria }
    end
  end

  # GET /galerias/new
  # GET /galerias/new.json
  def new
    @galeria = Galeria.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @galeria }
    end
  end

  # GET /galerias/1/edit
  def edit
    @galeria = Galeria.find(params[:id])
  end

  # POST /galerias
  # POST /galerias.json
  def create
    @galeria = Galeria.new(params[:galeria])

    respond_to do |format|
      if @galeria.save
        format.html { redirect_to @galeria, notice: 'Galeria was successfully created.' }
        format.json { render json: @galeria, status: :created, location: @galeria }
      else
        format.html { render action: "new" }
        format.json { render json: @galeria.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /galerias/1
  # PUT /galerias/1.json
  def update
    @galeria = Galeria.find(params[:id])

    respond_to do |format|
      if @galeria.update_attributes(params[:galeria])
        format.html { redirect_to @galeria, notice: 'Galeria was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @galeria.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galerias/1
  # DELETE /galerias/1.json
  def destroy
    @galeria = Galeria.find(params[:id])
    @galeria.destroy

    respond_to do |format|
      format.html { redirect_to galerias_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

def titulo(titulo_pagina)
	content_for (:titulo){titulo_pagina}
end

end

app/helpers/categorias_helper.rb
module CategoriasHelper
end

app/helpers/estaticas_helper.rb
module EstaticasHelper
end

app/helpers/galerias_helper.rb
module GaleriasHelper
end

app/views/categorias/_form.html.erb
<%= form_for(@categoria) do |f| %>
  <% if @categoria.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@categoria.errors.count, "error") %> prohibited this categoria from being saved:</h2>

      <ul>
      <% @categoria.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br />
    <%= f.text_field :titulo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categorias/edit.html.erb
<h1>Editing categoria</h1>

<%= render 'form' %>

<%= link_to 'Show', @categoria %> |
<%= link_to 'Back', categorias_path %>

app/views/categorias/index.html.erb
<h1>Listing categorias</h1>

<table>
  <tr>
    <th>Titulo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categorias.each do |categoria| %>
  <tr>
    <td><%= categoria.titulo %></td>
    <td><%= link_to 'Show', categoria %></td>
    <td><%= link_to 'Edit', edit_categoria_path(categoria) %></td>
    <td><%= link_to 'Destroy', categoria, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Categoria', new_categoria_path %>

app/views/categorias/new.html.erb
<h1>New categoria</h1>

<%= render 'form' %>

<%= link_to 'Back', categorias_path %>

app/views/categorias/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Titulo:</b>
  <%= @categoria.titulo %>
</p>

<% @galerias = @categoria.galerias %>
<% @galerias.each do |galeria| %>
		

<%= link_to 'Edit', edit_categoria_path(@categoria) %> 
<%= link_to 'Back', categorias_path %>

app/views/estaticas/vista1.html.erb
<% content_for :head do %>
	<%= javascript_include_tag "efectos" %>
<% end %>

<% titulo("Principal") %>

<h1>Estaticas#vista1</h1>

<% @todascategorias = Categoria.all %>
	<% if !@todascategorias.blank? %>
	<% for categorias in @todascategorias %>
		<div class="separaCategoria">
		 <h2><%= link_to categoria.titulo, categoria %></h2>
		<% @todasgalerias = categoria.galerias %>
		<% for galeria in @todasgalerias %>
			<div class="preview">
			<h2><%= link_to galeria.titulo, galeria %></h2>
			<%= image_tag galeria.imagen, :size => "50x50" %>
			</div>
		<% end %>
		
<div class="limpiarFloat">
</div>
</div>
	<% end %>
<% end %>

app/views/estaticas/vista2.html.erb
<% titulo("Segunda Vista") %>
<h1>Estaticas#vista2</h1>
<p>Find me in app/views/estaticas/vista2.html.erb</p>

app/views/estaticas/vista3.html.erb
<h1>Estaticas#vista3</h1>
<p>Find me in app/views/estaticas/vista3.html.erb</p>

app/views/estaticas/vista4.html.erb
<h1>Estaticas#vista4</h1>
<p>Find me in app/views/estaticas/vista4.html.erb</p>

app/views/galerias/_form.html.erb
<%= form_for(@galeria) do |f| %>
  <% if @galeria.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@galeria.errors.count, "error") %> prohibited this galeria from being saved:</h2>

      <ul>
      <% @galeria.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br />
    <%= f.text_field :titulo %>
  </div>
	<div class="field">
    	<%= f.label :categoria %><br />
    	<%= f.collection_select :categoria_id, Categoria.all, :id, :titulo %>
	</div>
  <div class="field">
    <%= f.label :descripcion %><br />
    <%= f.text_area :descripcion %>
  </div>
  <div class="field">
    <%= f.label :imagen %><br />
    <%= f.text_field :imagen %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/galerias/edit.html.erb
<h1>Editing galeria</h1>

<%= render 'form' %>

<%= link_to 'Show', @galeria %> |
<%= link_to 'Back', galerias_path %>

app/views/galerias/index.html.erb
<h1>Listing galerias</h1>

<table>
  <tr>
    <th>Titulo</th>
    <th>Descripcion</th>
    <th>Imagen</th>
    <th>Categoria</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @galerias.each do |galeria| %>
  <tr>
    <td><%= galeria.titulo %></td>
    <td><%= galeria.descripcion %></td>
    <td><%= image_tag galeria.imagen, :size => "70x70" %></td>
    <td><%= galeria.categoria.titulo %></td>
    <td><%= link_to 'Show', galeria %></td>
    <td><%= link_to 'Edit', edit_galeria_path(galeria) %></td>
    <td><%= link_to 'Destroy', galeria, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Galeria', new_galeria_path %>

app/views/galerias/new.html.erb
<h1>New galeria</h1>

<%= render 'form' %>

<%= link_to 'Back', galerias_path %>

app/views/galerias/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Titulo:</b>
  <%= @galeria.titulo %>
</p>

<p>
  <b>Descripcion:</b>
  <%= @galeria.descripcion %>
</p>

<p>
  <b>Imagen:</b>
  <%= image_tag @galeria.imagen %>
</p>

<p>
  <b>Categoria:</b>
  <%= @galeria.categoria.titulo %>
</p>


<%= link_to 'Edit', edit_galeria_path(@galeria) %> |
<%= link_to 'Back', galerias_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield (:titulo) || "Noticias Ultra-Relevantes" %></title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield :head %>
</head>
<body>

<div id="header">
			<%= image_tag "tunnel.gif", :size => "400x400" %>
</div>

<div id="contenedor">
	<ul>
		<li><%= link_to "Vista Uno", vistaUno_path %> </li>
		<li><%= link_to "Vista Dos", vistaDos_path %> </li>
		<li><%= link_to "Vista Tres", vistaTres_path %> </li>
		<li><%= link_to "Vista Cuatro", vistaCuatro_path %> </li>
		<li><%= link_to "Galerias", galerias_path %> </li>
		<li><%= link_to "Categorias", categorias_path %> </li>
	</ul>	

<%= yield %>

</div>
</body>
</html>